import type { Product } from "@/types";

/**
 * Static product catalog. In a real deployment this would come from a CMS or
 * commerce API via `lib/api.ts`; the shape is identical so swapping the source
 * requires no component changes.
 */
export const PRODUCTS: Product[] = [
  {
    id: "shots-blackcurrant",
    slug: "vitoshots-smorodina",
    name: "VITOSHOTS",
    format: "shots",
    category: "Шоты",
    flavor: "Смородина",
    description: "Жидкий коллагеновый курс",
    price: 650000,
    image: "/assets/shots-blue.webp",
    imageAlt: "VITOSHOTS — смородина",
    imageWidth: 1800,
    imageHeight: 1755,
    gradient: "grad-blue",
    imageWidthClass: "w-[78%]",
    badge: "popular",
  },
  {
    id: "shots-apple",
    slug: "vitoshots-yabloko",
    name: "VITOSHOTS",
    format: "shots",
    category: "Шоты",
    flavor: "Яблоко",
    description: "Жидкий коллагеновый курс",
    price: 650000,
    image: "/assets/shots-green.webp",
    imageAlt: "VITOSHOTS — яблоко",
    imageWidth: 1440,
    imageHeight: 1800,
    gradient: "grad-green",
    imageWidthClass: "w-[78%]",
  },
  {
    id: "shots-cherry",
    slug: "vitoshots-vishnya",
    name: "VITOSHOTS",
    format: "shots",
    category: "Шоты",
    flavor: "Вишня",
    description: "Жидкий коллагеновый курс",
    price: 650000,
    image: "/assets/shots-pink.webp",
    imageAlt: "VITOSHOTS — вишня",
    imageWidth: 1440,
    imageHeight: 1800,
    gradient: "grad-pink",
    imageWidthClass: "w-[78%]",
  },
  {
    id: "jelly-blackcurrant",
    slug: "kollagen-zhele-smorodina",
    name: "Коллаген желе",
    format: "jelly",
    category: "Желе",
    flavor: "Смородина",
    description: "Формат желе",
    price: 500000,
    image: "/assets/jelly-blue-big.webp",
    imageAlt: "Коллаген желе — смородина",
    imageWidth: 1080,
    imageHeight: 1350,
    gradient: "grad-blue",
    imageWidthClass: "w-[64%]",
    bigImage: "/assets/jelly-blue-xl.webp",
    bigImageWidth: 1000,
    bigImageHeight: 1250,
  },
  {
    id: "jelly-apple",
    slug: "kollagen-zhele-yabloko",
    name: "Коллаген желе",
    format: "jelly",
    category: "Желе",
    flavor: "Яблоко",
    description: "Формат желе",
    price: 500000,
    image: "/assets/jelly-green-big.webp",
    imageAlt: "Коллаген желе — яблоко",
    imageWidth: 1080,
    imageHeight: 1350,
    gradient: "grad-green",
    imageWidthClass: "w-[64%]",
    bigImage: "/assets/jelly-green-xl.webp",
    bigImageWidth: 1000,
    bigImageHeight: 1250,
  },
  {
    id: "jelly-cherry",
    slug: "kollagen-zhele-vishnya",
    name: "Коллаген желе",
    format: "jelly",
    category: "Желе",
    flavor: "Вишня",
    description: "Формат желе",
    price: 500000,
    image: "/assets/jelly-pink-big.webp",
    imageAlt: "Коллаген желе — вишня",
    imageWidth: 1080,
    imageHeight: 1350,
    gradient: "grad-pink",
    imageWidthClass: "w-[64%]",
    bigImage: "/assets/jelly-pink-xl.webp",
    bigImageWidth: 1000,
    bigImageHeight: 1250,
  },
];
