import type { Product } from "@/types";

/**
 * Static product catalog. In a real deployment this would come from a CMS or
 * commerce API via `lib/api.ts`; the shape is identical so swapping the source
 * requires no component changes.
 */
export const PRODUCTS: Product[] = [
  {
    id: "shots-blackcurrant",
    slug: "vitoshots-smorodina",
    name: "Жидкий морской коллаген",
    format: "shots",
    category: "Шоты",
    flavor: "Чёрная смородина",
    description: "Жидкий коллагеновый курс",
    price: 650000,
    image: "/assets/shots-blue.webp",
    imageAlt: "Жидкий морской коллаген — чёрная смородина",
    imageWidth: 1800,
    imageHeight: 1755,
    gradient: "grad-blue",
    imageWidthClass: "w-[78%]",
    gallery: ["/assets/pg-shots-box.webp", "/assets/pg-shots-vial.webp"],
    badge: "popular",
  },
  {
    id: "shots-apple",
    slug: "vitoshots-yabloko",
    name: "Жидкий морской коллаген",
    format: "shots",
    category: "Шоты",
    flavor: "Зелёное яблоко",
    description: "Жидкий коллагеновый курс",
    price: 650000,
    image: "/assets/shots-green.webp",
    imageAlt: "Жидкий морской коллаген — зелёное яблоко",
    imageWidth: 1440,
    imageHeight: 1800,
    gradient: "grad-green",
    imageWidthClass: "w-[78%]",
    gallery: ["/assets/pg-shots-green.webp", "/assets/pg-shots-box.webp"],
  },
  {
    id: "shots-cherry",
    slug: "vitoshots-vishnya",
    name: "Жидкий морской коллаген",
    format: "shots",
    category: "Шоты",
    flavor: "Вишня",
    description: "Жидкий коллагеновый курс",
    price: 650000,
    image: "/assets/shots-pink.webp",
    imageAlt: "Жидкий морской коллаген — вишня",
    imageWidth: 1440,
    imageHeight: 1800,
    gradient: "grad-pink",
    imageWidthClass: "w-[78%]",
    gallery: ["/assets/pg-shots-box.webp", "/assets/pg-shots-vial.webp"],
  },
  {
    id: "jelly-blackcurrant",
    slug: "kollagen-zhele-smorodina",
    name: "Морской коллаген желе",
    format: "jelly",
    category: "Желе",
    flavor: "Чёрная смородина",
    description: "Формат желе",
    price: 500000,
    image: "/assets/jelly-blue-big.webp",
    imageAlt: "Морской коллаген желе — чёрная смородина",
    imageWidth: 1080,
    imageHeight: 1350,
    gradient: "grad-blue",
    imageWidthClass: "w-[64%]",
    bigImage: "/assets/jelly-blue-xl.webp",
    bigImageWidth: 1000,
    bigImageHeight: 1250,
    gallery: ["/assets/pg-jelly-blue1.webp", "/assets/pg-jelly-blue2.webp"],
  },
  {
    id: "jelly-apple",
    slug: "kollagen-zhele-yabloko",
    name: "Морской коллаген желе",
    format: "jelly",
    category: "Желе",
    flavor: "Зелёное яблоко",
    description: "Формат желе",
    price: 500000,
    image: "/assets/jelly-green-big.webp",
    imageAlt: "Морской коллаген желе — зелёное яблоко",
    imageWidth: 1080,
    imageHeight: 1350,
    gradient: "grad-green",
    imageWidthClass: "w-[64%]",
    bigImage: "/assets/jelly-green-xl.webp",
    bigImageWidth: 1000,
    bigImageHeight: 1250,
    gallery: [
      "/assets/pg-jelly-apple1.webp",
      "/assets/pg-jelly-apple2.webp",
      "/assets/pg-jelly-apple-roses.webp",
    ],
  },
  {
    id: "jelly-cherry",
    slug: "kollagen-zhele-vishnya",
    name: "Морской коллаген желе",
    format: "jelly",
    category: "Желе",
    flavor: "Вишня",
    description: "Формат желе",
    price: 500000,
    image: "/assets/jelly-pink-big.webp",
    imageAlt: "Морской коллаген желе — вишня",
    imageWidth: 1080,
    imageHeight: 1350,
    gradient: "grad-pink",
    imageWidthClass: "w-[64%]",
    bigImage: "/assets/jelly-pink-xl.webp",
    bigImageWidth: 1000,
    bigImageHeight: 1250,
    gallery: [
      "/assets/pg-jelly-pink-roses.webp",
      "/assets/pg-jelly-wood1.webp",
      "/assets/pg-jelly-wood2.webp",
    ],
  },
];
